### PR TITLE
[ID-1014] GHA builds and version reporting

### PR DESCRIPTION
**Pull request by em-may**
### Ticket
https://broadworkbench.atlassian.net/browse/ID-1014

### What, Why, How
This repo currently uses CircleCI to build, test, and tag Bond images and git commits. The finished images are pushed to quay.io and need to be tagged with a semver by hand. This is very painful, not conducive to easy releases, and makes performing hotfixes take longer than necessary.

These changes use GHA to build, test, and tag Bond images and git commits. The finished images are pushed to Google Artifact Registry (GAR) which is the preferred image registry for DSP. Additionally, this PR reports app versions to Sherlock so that we can do things like set a BEE or live env to a specific version tag or branch name for testing or deployment. After this PR is merged and deployed to dev, we can add another job to automatically deploy the latest version to dev, and then have alpha follow dev, staging follow alpha, and prod follow staging, so that the versions are synced up to prod during the regular release cycle.

### Testing
I used the image generated by this PR in a BEE and Bond starts up fine.

### CircleCI
The CircleCI builds still run because Bond prod still needs those images for the Jenkins deploy job to GAE. We can remove them once bond-prod in k8s is being used and GAE is turned off.

### Speedup
The build now takes between 25-50% less time so that's nice.

---

Have you read [CONTRIBUTING.md](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md) lately? If not, do that first.

I, the developer opening this PR, do solemnly pinky swear that:

- [x] I've followed [the instructions](https://github.com/DataBiosphere/bond/blob/develop/CONTRIBUTING.md#api-changes) if I've made any changes to the API, _especially_ if they're breaking changes

In all cases:

- [x] Get two thumbsworth of review and PO signoff if necessary. 
- [x] Verify all tests go green
- [x] Squash and merge; you can delete your branch after this **unless it's for a hotfix**. In that case, don't delete it!
- [x] Test this change deployed correctly and works on dev environment after deployment
- [x] **Release to production** - Releasing to prod is a manual process (see [instructions to release to prod](https://github.com/DataBiosphere/bond/blob/develop/README.md#production-deployment-checklist)). Either do this now or create a ticket and schedule the release.

### CODE REVIEW

**Comment by tlangs** [comment]
Why was the trivy check removed?

**Comment by em-may** [comment]
It gets rolled into the build job as a step, which is pretty standard for our service build workflows.

**Comment by tlangs** [comment]
Oh whoops missed that in my initial viewing

**Review by tlangs — APPROVED** [review]

**Review by Ghost-in-a-Jar — APPROVED** [review]
this is frickin amazing thank you!!!!

**Pull request merged**
